# reports.py — SwytchAI Report Generator
import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.colors import HexColor
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate_compliance_pdf(report_data, org_name="SwytchAI"):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    elements = []

    # Title style
    title_style = ParagraphStyle("Title", parent=styles["Title"], fontSize=22, textColor=HexColor("#0a1929"), spaceAfter=6)
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"], fontSize=11, textColor=HexColor("#546e7a"), spaceAfter=20)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"], fontSize=14, textColor=HexColor("#0a1929"), spaceBefore=16, spaceAfter=8)
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, textColor=HexColor("#37474f"), spaceAfter=6)

    # Header
    elements.append(Paragraph(f"{org_name} — Compliance Report", title_style))
    elements.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", subtitle_style))
    elements.append(Paragraph(f"Device: {report_data.get('device', 'Unknown')}", body_style))
    elements.append(Spacer(1, 12))

    # Score summary
    score = report_data.get("score", 0)
    passed = report_data.get("passed", 0)
    failed = report_data.get("failed", 0)
    total = report_data.get("total", 0)

    score_color = "#2e7d32" if score >= 80 else "#f57c00" if score >= 50 else "#c62828"
    score_style = ParagraphStyle("Score", parent=styles["Normal"], fontSize=18, textColor=HexColor(score_color), spaceAfter=4)

    elements.append(Paragraph("Compliance Score", heading_style))
    elements.append(Paragraph(f"{score}%", score_style))
    elements.append(Paragraph(f"{passed} passed | {failed} failed | {total} total rules", body_style))
    elements.append(Spacer(1, 16))

    # Results table
    elements.append(Paragraph("Detailed Results", heading_style))

    table_data = [["Rule", "Severity", "Status", "Remediation"]]
    for r in report_data.get("results", []):
        status = "PASS" if r["passed"] else "FAIL"
        fix = r.get("fix", "") or "—"
        table_data.append([r["name"], r["severity"].upper(), status, fix])

    table = Table(table_data, colWidths=[2*inch, 1*inch, 0.75*inch, 3*inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#0a1929")),
        ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#ffffff")),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("ALIGN", (1, 0), (2, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#cfd8dc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#ffffff"), HexColor("#f5f5f5")]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 20))

    # Footer
    elements.append(Paragraph(f"Report generated by {org_name} powered by SwytchAI", ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=HexColor("#90a4ae"))))

    doc.build(elements)
    buffer.seek(0)
    return buffer


def generate_device_report_pdf(devices, org_name="SwytchAI"):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle("Title", parent=styles["Title"], fontSize=22, textColor=HexColor("#0a1929"), spaceAfter=6)
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"], fontSize=11, textColor=HexColor("#546e7a"), spaceAfter=20)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"], fontSize=14, textColor=HexColor("#0a1929"), spaceBefore=16, spaceAfter=8)

    elements.append(Paragraph(f"{org_name} — Device Inventory Report", title_style))
    elements.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", subtitle_style))
    elements.append(Paragraph(f"Total Devices: {len(devices)}", subtitle_style))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("Device Inventory", heading_style))

    table_data = [["Hostname", "Host/IP", "Vendor", "Added By"]]
    for d in devices:
        table_data.append([d.get("hostname", ""), d.get("host", ""), d.get("vendor", ""), d.get("added_by", "")])

    table = Table(table_data, colWidths=[2*inch, 2.25*inch, 1.25*inch, 1.25*inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#0a1929")),
        ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#ffffff")),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#cfd8dc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#ffffff"), HexColor("#f5f5f5")]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 20))

    elements.append(Paragraph(f"Report generated by {org_name} powered by SwytchAI", ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=HexColor("#90a4ae"))))

    doc.build(elements)
    buffer.seek(0)
    return buffer
